### PR TITLE
chore: auto redirect with countdown fixes #508

### LINKED ISSUE #508: Make the redirection from the 404 page to the home page automatic
Instead of prompting the user to push a button to be redirected to the home page from broken links, display a message stating that the link is broken and automatically redirect the user

### PR DESCRIPTION
**Pull request by SimonAM**
Fixes #508

### CODE REVIEW

**Comment by elvbom** [comment]
@SimonAM, it seems like you need to run the lint command (npx eslint . --ext .js,.jsx,.ts,.tsx --fix), a few minor issues that need attention.

**Comment by elvbom** [comment]
Tack för denna PR! Vi tittar på den efter ledigheten, bra jobbat!

**Comment by LudwikJaniuk** [comment]
Please merge with Staging!

**Comment by SimonAM** [comment]
Thanks for the feedback!
Its now merged with staging and linted.

**Comment by LudwikJaniuk** [comment]
It's looking mostly good, but - on my computer it counts down like "9", "7", "5"... it skips the even numbers. I think there is something slightly off about the React logic here. 

In https://github.com/Klimatbyran/klimatkollen/issues/508 @Greenheart also talked about a toast component, which isn't what we have here, but I assume we can live with the current implementation.

**Pull request merged**
